config/_default/params.yaml
content/about-us/_index.md
content/about-us/community.md
content/about-us/contact.md
content/about-us/funding.md
content/about-us/impact.md
content/about-us/team.md

Add more pages and content to "about" pages section

---

config/_default/params.yaml
content/workshops/_index.md
content/workshops/request-workshop.md
content/workshops/workshops-faq.md

Explores how to set up content, adjust menus, etc. on the workshops section.

Workshops pages

---

config/_default/menus.yaml
content/instructor-training/_index.md

Set up instructor training section

Instructor training pages

---

config/_default/menus.yaml
content/about-us/_index.md
content/about-us/community.md
content/about-us/contact.md
content/about-us/funding.md
content/about-us/impact.md
content/about-us/no-sidebar.md
content/about-us/team.md
content/workshops/_index.md
content/workshops/request-workshop.md
content/workshops/workshops-faq.md
themes/carpentries/layouts/partials/subnav.html

Modularize tabbed navigation

---

content/search.md
netlify.toml
themes/carpentries/i18n/en.yaml
themes/carpentries/layouts/_default/baseof.html
themes/carpentries/layouts/shortcodes/search.html

Include site-wide general search

---

themes/carpentries/layouts/partials/func/ParseWorkshop.html

adjust online/in-person logic

---

content/modules.md
themes/carpentries/layouts/shortcodes/feed_value.html

Option to dynamically generate statistics

---

config/_default/params.yaml
content/about-us/newsletter.md
themes/carpentries/layouts/shortcodes/mc_newsletter_form.html
themes/carpentries/layouts/shortcodes/newsletter_archive.html

Addresses #49
Fixes #58
Fixes #59

Create newsletter page

---

config/_default/menus.yaml
content/workshops/_index.md

Sets up structure & content for workshops section.

Fix workshops section

---

config/_default/menus.yaml
config/_default/params.yaml
content/instructor-training/_index.md
content/instructor-training/instructor-training-faq.md

Updates IT section, including setting up placeholder FAQ page and tabbed menu navigation.

Fix instructor training section

---

config/_default/menus.yaml
config/_default/params.yaml
content/host/host-training.md
content/host/host-workshop.md
content/host/pricing.md

Create pages to host workshop, host training, and pricing.

Create host pages

---

config/_default/markup.yaml
themes/carpentries/assets/css/styles.css
themes/carpentries/layouts/_default/list.html
themes/carpentries/layouts/_default/single.html
themes/carpentries/layouts/_default/workshops.html
themes/carpentries/layouts/shortcodes/toc.html

start of TOC widget

---

assets/js/filters.js
themes/carpentries/layouts/_default/lessons.html
themes/carpentries/layouts/_default/list-feedback.html
themes/carpentries/layouts/_default/workshops.html

Display text if no search results found

---

config/_default/frontmatter.yaml

Coerce blog dates from file names

---

themes/carpentries/layouts/_default/terms.html
themes/carpentries/layouts/partials/widgets/meta.html
themes/carpentries/layouts/post/date.html

adjust date format

---

themes/carpentries/layouts/_default/terms.html

View blog posts by author and title

---

themes/carpentries/layouts/partials/footer-branding.html
themes/carpentries/layouts/partials/footer-legal-social.html
themes/carpentries/layouts/partials/footer-menu.html
themes/carpentries/layouts/partials/footer.html

remove hard coded content in footer

---

themes/carpentries/hugo.yaml
themes/carpentries/layouts/_default/terms.html
themes/carpentries/layouts/partials/widgets/meta.html
themes/carpentries/layouts/post/date.html

Use site parameters to set default date format

set site params for default date format

---

config/_default/menus.yaml
config/_default/params.yaml
themes/carpentries/layouts/partials/footer-branding.html
themes/carpentries/layouts/partials/footer-menu.html
themes/carpentries/layouts/partials/footer-submenu.html

Set up footer menus in the menus.yaml file, and the overview text in the site config file

abstract menu and over view text out of template

---

themes/carpentries/layouts/partials/footer-legal-social.html

no URL makes icon / link go away

adjusted so URL controls visibility of link

---

config/_default/params.yaml
themes/carpentries/layouts/partials/footer-legal-social.html

move donate link to params

---

themes/carpentries/layouts/partials/blocks/templates/select-cta.html

remove go button

---

themes/carpentries/layouts/_default/lessons.html
themes/carpentries/layouts/_default/workshops.html
themes/carpentries/layouts/partials/filters.html
themes/carpentries/layouts/partials/func/GetFiltersFromEntries.html

Filter heading should not be hard coded

---

data/curricula.yaml

Addresses #109 by setting up a yaml curriculum list.

set up curriculum list

---

themes/carpentries/layouts/partials/func/GetCurriculums.html
themes/carpentries/layouts/partials/func/GetFiltersFromEntries.html
themes/carpentries/layouts/partials/func/ParseCurriculum.html

Workshops filter by curriculum (new)
